spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 266231457092-inec22rqqheedrrve9132n0j2sapno69.apps.googleusercontent.com # Updated with new Google OAuth Client ID

cloudinary:
    cloud-name: depaiphq0
    api-key: 746389516589297
    api-secret: IurXYsZYcLEgvQicz-200t8OMDM