insert into genre(name, description, created_by)
value ('Hành động', 'Phim hành động là thể loại phim tập trung vào những cảnh quay kịch tính, thường có nhiều pha hành động, chiến đấu, và mạo hiểm. Những bộ phim này thường mang đến cho khán giả cảm giác hồi hộp và kích thích.', 'admin'),
    ('Phiêu lưu', 'Phim phiêu lưu là thể loại phim tập trung vào những cuộc hành trình, khám phá, và trải nghiệm mới. Những bộ phim này thường có cốt truyện hấp dẫn, với những tình tiết ly kỳ và những cảnh quay đẹp mắt.', 'admin'),
    ('Hài hước', 'Phim hài hước là thể loại phim tập trung vào việc tạo ra tiếng cười và giải trí cho khán giả. Những bộ phim này thường có những tình huống hài hước, những nhân vật vui nhộn, và những câu thoại dí dỏm.', 'admin'),
    ('Kinh dị', 'Phim kinh dị là thể loại phim tập trung vào việc tạo ra sự sợ hãi và căng thẳng cho khán giả. Những bộ phim này thường có những cảnh quay đáng sợ, những tình tiết ly kỳ, và những nhân vật đáng sợ.', 'admin'),
    ('Lãng mạng','Phim lãng mạng là thể loại phim tập trung vào việc kể chuyện về những mối quan hệ tình cảm, tình yêu và các vấn đề liên quan đến đời sống hôn nhân, gia đình.', 'admin'),
    ('Khoa học viễn tưởng', 'Phim khoa học viễn tưởng là thể loại phim tập trung vào những câu chuyện về công nghệ, không gian, thời gian, và các hiện tượng siêu nhiên. Những bộ phim này thường có những cảnh quay đẹp mắt và những tình tiết ly kỳ.', 'admin'),
    ('Tâm lý', 'Phim tâm lý là thể loại phim tập trung vào việc khám phá tâm lý của nhân vật và các mối quan hệ giữa họ. Những bộ phim này thường có những tình tiết phức tạp và những nhân vật sâu sắc.', 'admin'),
    ('Hoạt hình', 'Phim hoạt hình là thể loại phim sử dụng kỹ thuật hoạt hình để tạo ra hình ảnh và chuyển động. Những bộ phim này thường có những câu chuyện hấp dẫn và những nhân vật đáng yêu, phù hợp với mọi lứa tuổi.', 'admin');
